{{- if (not .Values.inPodPostgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "db.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
 {{ if .Values.useInPodPostgres }}
  {{ if .Values.inPodPostgres.postgresPassword }}
  dbPassword:  {{ .Values.inPodPostgres.postgresPassword | b64enc | quote }}
  {{ else }}
  dbPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
 {{ else if .Values.externalDB }}
  dbHost: {{ .Values.externalDB.dbHost | b64enc | quote }}
  dbPort: {{ .Values.externalDB.dbPort | b64enc | quote }}
  dbUser: {{ .Values.externalDB.dbUser | b64enc | quote }}
  dbPassword: {{ .Values.externalDB.dbPassword | b64enc | quote }}
  dbDatabase: {{ .Values.externalDB.dbDatabase | b64enc | quote }}
 {{- end }}
{{- end }}
