{{- if .Values.ingress.enabled  }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.ingress.ingress_annotations | indent 4 }}
spec:
  rules:
  - host: {{ .Values.service.http.externalHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}-http
          servicePort: {{ .Values.service.http.port }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
